name: ops-cron-email

on:
  schedule:
    - cron: "*/5 * * * *"   # cada 5 minutos (UTC)
  workflow_dispatch: {}      # puedes lanzarlo manualmente

jobs:
  run-ops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # (opcional) ver el árbol para confirmar rutas
      - name: Debug tree
        run: |
          pwd
          ls -la

      - name: Install deps
        run: npm ci
        working-directory: ./

      - name: SLA Watcher
        run: npm run sla:run
        working-directory: ./
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}

      - name: Notifier (email only)
        run: npm run notify:email
        working-directory: ./
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
